---
apiVersion: apps/v1
kind: Deployment                
metadata:
  name: orders          
spec:
  replicas: 1                   
  selector:
    matchLabels:
      app: orders        
  template:                      
    metadata:
      labels:                    
        app: orders
    spec:                        
      containers:
      - name: orders-service
        image: geraz14/golang
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8100   