apiVersion: v1
kind: Service
metadata:
  name: catalog-service
  labels:
    run: catalog-service
spec:
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
  type: NodePort
  selector:
    run: catalog
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog
  labels:
    app: catalog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalog
  template:
    metadata:
      labels:
        app: catalog
    spec:
      containers:
      - name: catalog-service
        image: geraz14/catalog-service
        ports:
        - containerPort: 3000